****cv 0 / 5 ****
INFO:runner.model.base_runner:****cv 0 / 5 ****
/home/yohyohyonyon/kaggle/vbs-power-line-fault-detection/model/custom_nn.py:256: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  nn.init.xavier_uniform(m.weight.data)
INFO:model.nn_model_wrapper:train with data size: 2322
INFO:model.nn_model_wrapper:valid with data size: 582
  0%|          | 0/300 [00:00<?, ?it/s]INFO:model.nn_model_wrapper:training 1  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 1: 0.2326843 :
INFO:model.nn_model_wrapper:******train score at epoch 1: -0.01647 :
INFO:model.nn_model_wrapper:******valid loss at epoch 1: 0.0540424 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 1: 0.00000 :
INFO:model.nn_model_wrapper:validation metric is improved from -inf to -0.05404
INFO:model.nn_model_wrapper:Checkpoint saved
  0%|          | 1/300 [00:02<11:18,  2.27s/it]INFO:model.nn_model_wrapper:training 2  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 2: 0.0612195 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 2: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 2: 0.0569783 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 2: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
  1%|          | 2/300 [00:04<10:58,  2.21s/it]INFO:model.nn_model_wrapper:training 3  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 3: 0.0607730 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 3: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 3: 0.0674588 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 3: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
  1%|          | 3/300 [00:06<10:38,  2.15s/it]INFO:model.nn_model_wrapper:training 4  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 4: 0.0603718 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 4: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 4: 0.0629670 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 4: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
  1%|▏         | 4/300 [00:08<10:26,  2.12s/it]INFO:model.nn_model_wrapper:training 5  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 5: 0.0611731 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 5: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 5: 0.0629670 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 5: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
  2%|▏         | 5/300 [00:10<10:17,  2.09s/it]INFO:model.nn_model_wrapper:training 6  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 6: 0.0615745 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 6: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 6: 0.0599725 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 6: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
  2%|▏         | 6/300 [00:12<10:07,  2.07s/it]INFO:model.nn_model_wrapper:training 7  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 7: 0.0609725 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 7: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 7: 0.0614698 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 7: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
  2%|▏         | 7/300 [00:14<09:54,  2.03s/it]INFO:model.nn_model_wrapper:training 8  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 8: 0.0617749 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 8: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 8: 0.0659615 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 8: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
  3%|▎         | 8/300 [00:16<09:45,  2.00s/it]INFO:model.nn_model_wrapper:training 9  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 9: 0.0621762 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 9: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 9: 0.0599725 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 9: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
  3%|▎         | 9/300 [00:18<09:40,  1.99s/it]INFO:model.nn_model_wrapper:training 10  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 10: 0.0613738 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 10: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 10: 0.0644643 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 10: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
  3%|▎         | 10/300 [00:20<09:35,  1.98s/it]INFO:model.nn_model_wrapper:training 11  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 11: 0.0617750 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 11: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 11: 0.0689560 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 11: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
  4%|▎         | 11/300 [00:22<09:43,  2.02s/it]INFO:model.nn_model_wrapper:training 12  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 12: 0.0609726 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 12: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 12: 0.0629670 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 12: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
  4%|▍         | 12/300 [00:24<09:38,  2.01s/it]INFO:model.nn_model_wrapper:training 13  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 13: 0.0609726 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 13: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 13: 0.0599725 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 13: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
  4%|▍         | 13/300 [00:26<09:40,  2.02s/it]INFO:model.nn_model_wrapper:training 14  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 14: 0.0607718 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 14: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 14: 0.0614698 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 14: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
  5%|▍         | 14/300 [00:28<09:32,  2.00s/it]INFO:model.nn_model_wrapper:training 15  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 15: 0.0603706 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 15: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 15: 0.0614698 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 15: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
  5%|▌         | 15/300 [00:30<09:31,  2.01s/it]INFO:model.nn_model_wrapper:training 16  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 16: 0.0613738 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 16: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 16: 0.0539835 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 16: 0.00000 :
INFO:model.nn_model_wrapper:validation metric is improved from -0.05404 to -0.05398
INFO:model.nn_model_wrapper:Checkpoint saved
  5%|▌         | 16/300 [00:32<09:31,  2.01s/it]INFO:model.nn_model_wrapper:training 17  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 17: 0.0609725 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 17: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 17: 0.0584753 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 17: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
  6%|▌         | 17/300 [00:34<09:35,  2.03s/it]INFO:model.nn_model_wrapper:training 18  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 18: 0.0617752 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 18: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 18: 0.0599725 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 18: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
  6%|▌         | 18/300 [00:36<09:26,  2.01s/it]INFO:model.nn_model_wrapper:training 19  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 19: 0.0609726 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 19: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 19: 0.0674588 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 19: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
  6%|▋         | 19/300 [00:38<09:22,  2.00s/it]INFO:model.nn_model_wrapper:training 20  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 20: 0.0611733 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 20: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 20: 0.0584753 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 20: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
  7%|▋         | 20/300 [00:40<09:12,  1.97s/it]INFO:model.nn_model_wrapper:training 21  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 21: 0.0613738 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 21: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 21: 0.0584753 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 21: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
  7%|▋         | 21/300 [00:42<09:10,  1.97s/it]INFO:model.nn_model_wrapper:training 22  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 22: 0.0607719 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 22: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 22: 0.0584753 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 22: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
  7%|▋         | 22/300 [00:44<09:05,  1.96s/it]INFO:model.nn_model_wrapper:training 23  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 23: 0.0609729 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 23: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 23: 0.0599725 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 23: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
  8%|▊         | 23/300 [00:46<09:05,  1.97s/it]INFO:model.nn_model_wrapper:training 24  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 24: 0.0605713 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 24: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 24: 0.0644643 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 24: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
  8%|▊         | 24/300 [00:48<09:03,  1.97s/it]INFO:model.nn_model_wrapper:training 25  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 25: 0.0603706 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 25: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 25: 0.0674588 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 25: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
  8%|▊         | 25/300 [00:50<09:06,  1.99s/it]INFO:model.nn_model_wrapper:training 26  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 26: 0.0611732 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 26: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 26: 0.0674588 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 26: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
  9%|▊         | 26/300 [00:52<09:07,  2.00s/it]INFO:model.nn_model_wrapper:training 27  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 27: 0.0617752 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 27: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 27: 0.0644643 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 27: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
  9%|▉         | 27/300 [00:54<09:09,  2.01s/it]INFO:model.nn_model_wrapper:training 28  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 28: 0.0605713 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 28: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 28: 0.0599725 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 28: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
  9%|▉         | 28/300 [00:56<09:09,  2.02s/it]INFO:model.nn_model_wrapper:training 29  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 29: 0.0607721 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 29: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 29: 0.0689560 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 29: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 10%|▉         | 29/300 [00:58<08:59,  1.99s/it]INFO:model.nn_model_wrapper:training 30  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 30: 0.0613744 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 30: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 30: 0.0629670 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 30: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 10%|█         | 30/300 [01:00<08:56,  1.99s/it]INFO:model.nn_model_wrapper:training 31  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 31: 0.0619758 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 31: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 31: 0.0629670 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 31: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 10%|█         | 31/300 [01:02<09:02,  2.02s/it]INFO:model.nn_model_wrapper:training 32  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 32: 0.0607722 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 32: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 32: 0.0644643 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 32: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 11%|█         | 32/300 [01:04<08:58,  2.01s/it]INFO:model.nn_model_wrapper:training 33  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 33: 0.0611734 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 33: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 33: 0.0569780 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 33: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 11%|█         | 33/300 [01:06<08:59,  2.02s/it]INFO:model.nn_model_wrapper:training 34  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 34: 0.0607719 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 34: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 34: 0.0524863 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 34: 0.00000 :
INFO:model.nn_model_wrapper:validation metric is improved from -0.05398 to -0.05249
INFO:model.nn_model_wrapper:Checkpoint saved
 11%|█▏        | 34/300 [01:08<09:00,  2.03s/it]INFO:model.nn_model_wrapper:training 35  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 35: 0.0621763 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 35: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 35: 0.0554808 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 35: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 12%|█▏        | 35/300 [01:10<08:53,  2.01s/it]INFO:model.nn_model_wrapper:training 36  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 36: 0.0609725 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 36: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 36: 0.0614698 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 36: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 12%|█▏        | 36/300 [01:12<08:56,  2.03s/it]INFO:model.nn_model_wrapper:training 37  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 37: 0.0617751 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 37: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 37: 0.0614698 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 37: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 12%|█▏        | 37/300 [01:14<08:51,  2.02s/it]INFO:model.nn_model_wrapper:training 38  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 38: 0.0617752 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 38: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 38: 0.0674588 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 38: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 13%|█▎        | 38/300 [01:16<08:42,  1.99s/it]INFO:model.nn_model_wrapper:training 39  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 39: 0.0607722 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 39: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 39: 0.0689561 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 39: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 13%|█▎        | 39/300 [01:18<08:33,  1.97s/it]INFO:model.nn_model_wrapper:training 40  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 40: 0.0611732 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 40: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 40: 0.0554808 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 40: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 13%|█▎        | 40/300 [01:20<08:33,  1.97s/it]INFO:model.nn_model_wrapper:training 41  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 41: 0.0615746 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 41: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 41: 0.0614698 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 41: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 14%|█▎        | 41/300 [01:22<08:28,  1.96s/it]INFO:model.nn_model_wrapper:training 42  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 42: 0.0609727 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 42: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 42: 0.0599725 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 42: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 14%|█▍        | 42/300 [01:24<08:34,  1.99s/it]INFO:model.nn_model_wrapper:training 43  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 43: 0.0617751 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 43: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 43: 0.0614698 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 43: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 14%|█▍        | 43/300 [01:26<08:25,  1.97s/it]INFO:model.nn_model_wrapper:training 44  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 44: 0.0607721 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 44: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 44: 0.0629670 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 44: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 15%|█▍        | 44/300 [01:28<08:19,  1.95s/it]INFO:model.nn_model_wrapper:training 45  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 45: 0.0619758 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 45: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 45: 0.0584753 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 45: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 15%|█▌        | 45/300 [01:30<08:28,  1.99s/it]INFO:model.nn_model_wrapper:training 46  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 46: 0.0607720 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 46: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 46: 0.0689561 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 46: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 15%|█▌        | 46/300 [01:32<08:29,  2.00s/it]INFO:model.nn_model_wrapper:training 47  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 47: 0.0613739 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 47: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 47: 0.0629670 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 47: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 16%|█▌        | 47/300 [01:34<08:26,  2.00s/it]INFO:model.nn_model_wrapper:training 48  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 48: 0.0613739 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 48: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 48: 0.0599725 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 48: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 16%|█▌        | 48/300 [01:36<08:33,  2.04s/it]INFO:model.nn_model_wrapper:training 49  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 49: 0.0629788 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 49: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 49: 0.0644643 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 49: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 16%|█▋        | 49/300 [01:38<08:28,  2.03s/it]INFO:model.nn_model_wrapper:training 50  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 50: 0.0611735 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 50: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 50: 0.0674588 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 50: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 17%|█▋        | 50/300 [01:40<08:33,  2.05s/it]INFO:model.nn_model_wrapper:training 51  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 51: 0.0609727 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 51: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 51: 0.0614698 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 51: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 17%|█▋        | 51/300 [01:42<08:33,  2.06s/it]INFO:model.nn_model_wrapper:training 52  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 52: 0.0613741 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 52: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 52: 0.0629671 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 52: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 17%|█▋        | 52/300 [01:44<08:32,  2.07s/it]INFO:model.nn_model_wrapper:training 53  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 53: 0.0611737 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 53: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 53: 0.0629671 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 53: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 18%|█▊        | 53/300 [01:46<08:22,  2.03s/it]INFO:model.nn_model_wrapper:training 54  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 54: 0.0609728 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 54: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 54: 0.0584753 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 54: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 18%|█▊        | 54/300 [01:48<08:11,  2.00s/it]INFO:model.nn_model_wrapper:training 55  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 55: 0.0619761 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 55: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 55: 0.0599726 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 55: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 18%|█▊        | 55/300 [01:50<08:06,  1.98s/it]INFO:model.nn_model_wrapper:training 56  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 56: 0.0617753 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 56: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 56: 0.0644643 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 56: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 19%|█▊        | 56/300 [01:52<08:03,  1.98s/it]INFO:model.nn_model_wrapper:training 57  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 57: 0.0611733 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 57: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 57: 0.0554808 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 57: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 19%|█▉        | 57/300 [01:54<08:06,  2.00s/it]INFO:model.nn_model_wrapper:training 58  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 58: 0.0617753 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 58: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 58: 0.0599726 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 58: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 19%|█▉        | 58/300 [01:56<08:06,  2.01s/it]INFO:model.nn_model_wrapper:training 59  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 59: 0.0613741 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 59: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 59: 0.0599726 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 59: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 20%|█▉        | 59/300 [01:58<08:04,  2.01s/it]INFO:model.nn_model_wrapper:training 60  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 60: 0.0607729 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 60: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 60: 0.0599726 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 60: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 20%|██        | 60/300 [02:00<08:04,  2.02s/it]INFO:model.nn_model_wrapper:training 61  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 61: 0.0609728 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 61: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 61: 0.0629671 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 61: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 20%|██        | 61/300 [02:02<08:07,  2.04s/it]INFO:model.nn_model_wrapper:training 62  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 62: 0.0609729 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 62: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 62: 0.0644643 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 62: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 21%|██        | 62/300 [02:04<08:09,  2.06s/it]INFO:model.nn_model_wrapper:training 63  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 63: 0.0613742 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 63: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 63: 0.0614698 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 63: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 21%|██        | 63/300 [02:06<08:06,  2.05s/it]INFO:model.nn_model_wrapper:training 64  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 64: 0.0609735 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 64: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 64: 0.0644643 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 64: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 21%|██▏       | 64/300 [02:08<08:01,  2.04s/it]INFO:model.nn_model_wrapper:training 65  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 65: 0.0603710 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 65: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 65: 0.0614698 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 65: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 22%|██▏       | 65/300 [02:10<08:04,  2.06s/it]INFO:model.nn_model_wrapper:training 66  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 66: 0.0615758 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 66: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 66: 0.0569781 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 66: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 22%|██▏       | 66/300 [02:12<08:04,  2.07s/it]INFO:model.nn_model_wrapper:training 67  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 67: 0.0627792 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 67: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 67: 0.0524863 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 67: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 22%|██▏       | 67/300 [02:14<07:59,  2.06s/it]INFO:model.nn_model_wrapper:training 68  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 68: 0.0609735 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 68: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 68: 0.0674588 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 68: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 23%|██▎       | 68/300 [02:16<07:53,  2.04s/it]INFO:model.nn_model_wrapper:training 69  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 69: 0.0615750 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 69: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 69: 0.0674588 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 69: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 23%|██▎       | 69/300 [02:19<07:51,  2.04s/it]INFO:model.nn_model_wrapper:training 70  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 70: 0.0607724 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 70: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 70: 0.0569781 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 70: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 23%|██▎       | 70/300 [02:20<07:40,  2.00s/it]INFO:model.nn_model_wrapper:training 71  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 71: 0.0605719 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 71: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 71: 0.0629671 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 71: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 24%|██▎       | 71/300 [02:22<07:39,  2.01s/it]INFO:model.nn_model_wrapper:training 72  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 72: 0.0605718 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 72: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 72: 0.0659616 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 72: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 24%|██▍       | 72/300 [02:24<07:31,  1.98s/it]INFO:model.nn_model_wrapper:training 73  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 73: 0.0615751 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 73: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 73: 0.0614698 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 73: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 24%|██▍       | 73/300 [02:26<07:32,  1.99s/it]INFO:model.nn_model_wrapper:training 74  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 74: 0.0605723 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 74: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 74: 0.0719506 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 74: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 25%|██▍       | 74/300 [02:28<07:35,  2.02s/it]INFO:model.nn_model_wrapper:training 75  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 75: 0.0613741 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 75: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 75: 0.0599726 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 75: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 25%|██▌       | 75/300 [02:30<07:27,  1.99s/it]INFO:model.nn_model_wrapper:training 76  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 76: 0.0601716 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 76: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 76: 0.0629671 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 76: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 25%|██▌       | 76/300 [02:32<07:20,  1.96s/it]INFO:model.nn_model_wrapper:training 77  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 77: 0.0609736 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 77: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 77: 0.0644643 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 77: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 26%|██▌       | 77/300 [02:34<07:20,  1.98s/it]INFO:model.nn_model_wrapper:training 78  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 78: 0.0617750 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 78: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 78: 0.0689561 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 78: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 26%|██▌       | 78/300 [02:36<07:26,  2.01s/it]INFO:model.nn_model_wrapper:training 79  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 79: 0.0611743 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 79: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 79: 0.0629671 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 79: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 26%|██▋       | 79/300 [02:38<07:21,  2.00s/it]INFO:model.nn_model_wrapper:training 80  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 80: 0.0601703 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 80: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 80: 0.0629671 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 80: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 27%|██▋       | 80/300 [02:40<07:12,  1.97s/it]INFO:model.nn_model_wrapper:training 81  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 81: 0.0605725 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 81: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 81: 0.0644644 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 81: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 27%|██▋       | 81/300 [02:42<07:17,  2.00s/it]INFO:model.nn_model_wrapper:training 82  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 82: 0.0615756 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 82: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 82: 0.0689561 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 82: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 27%|██▋       | 82/300 [02:44<07:16,  2.00s/it]INFO:model.nn_model_wrapper:training 83  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 83: 0.0627809 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 83: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 83: 0.0614699 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 83: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 28%|██▊       | 83/300 [02:46<07:12,  1.99s/it]INFO:model.nn_model_wrapper:training 84  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 84: 0.0599706 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 84: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 84: 0.0644644 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 84: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 28%|██▊       | 84/300 [02:48<07:10,  1.99s/it]INFO:model.nn_model_wrapper:training 85  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 85: 0.0611739 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 85: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 85: 0.0719506 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 85: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 28%|██▊       | 85/300 [02:50<07:14,  2.02s/it]INFO:model.nn_model_wrapper:training 86  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 86: 0.0605722 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 86: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 86: 0.0554808 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 86: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 29%|██▊       | 86/300 [02:52<07:15,  2.04s/it]INFO:model.nn_model_wrapper:training 87  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 87: 0.0617758 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 87: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 87: 0.0689561 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 87: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 29%|██▉       | 87/300 [02:55<07:15,  2.05s/it]INFO:model.nn_model_wrapper:training 88  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 88: 0.0605719 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 88: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 88: 0.0554808 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 88: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 29%|██▉       | 88/300 [02:57<07:08,  2.02s/it]INFO:model.nn_model_wrapper:training 89  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 89: 0.0601708 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 89: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 89: 0.0584753 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 89: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 30%|██▉       | 89/300 [02:58<07:04,  2.01s/it]INFO:model.nn_model_wrapper:training 90  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 90: 0.0611733 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 90: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 90: 0.0554808 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 90: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 30%|███       | 90/300 [03:01<07:04,  2.02s/it]INFO:model.nn_model_wrapper:training 91  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 91: 0.0603713 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 91: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 91: 0.0614698 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 91: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 30%|███       | 91/300 [03:03<07:00,  2.01s/it]INFO:model.nn_model_wrapper:training 92  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 92: 0.0617751 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 92: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 92: 0.0599726 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 92: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 31%|███       | 92/300 [03:05<07:01,  2.03s/it]INFO:model.nn_model_wrapper:training 93  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 93: 0.0611740 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 93: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 93: 0.0614698 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 93: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 31%|███       | 93/300 [03:07<07:02,  2.04s/it]INFO:model.nn_model_wrapper:training 94  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 94: 0.0619761 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 94: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 94: 0.0689561 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 94: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 31%|███▏      | 94/300 [03:09<06:58,  2.03s/it]INFO:model.nn_model_wrapper:training 95  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 95: 0.0599704 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 95: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 95: 0.0584753 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 95: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 32%|███▏      | 95/300 [03:11<06:49,  2.00s/it]INFO:model.nn_model_wrapper:training 96  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 96: 0.0607725 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 96: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 96: 0.0599726 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 96: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 32%|███▏      | 96/300 [03:13<06:50,  2.01s/it]INFO:model.nn_model_wrapper:training 97  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 97: 0.0611738 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 97: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 97: 0.0584753 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 97: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 32%|███▏      | 97/300 [03:15<06:46,  2.00s/it]INFO:model.nn_model_wrapper:training 98  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 98: 0.0621769 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 98: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 98: 0.0644643 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 98: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 33%|███▎      | 98/300 [03:17<06:44,  2.00s/it]INFO:model.nn_model_wrapper:training 99  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 99: 0.0611736 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 99: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 99: 0.0599726 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 99: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 33%|███▎      | 99/300 [03:19<06:46,  2.02s/it]INFO:model.nn_model_wrapper:training 100  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 100: 0.0607727 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 100: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 100: 0.0689561 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 100: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 33%|███▎      | 100/300 [03:21<06:45,  2.03s/it]INFO:model.nn_model_wrapper:training 101  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 101: 0.0609732 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 101: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 101: 0.0569782 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 101: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 34%|███▎      | 101/300 [03:23<06:41,  2.02s/it]INFO:model.nn_model_wrapper:training 102  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 102: 0.0605722 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 102: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 102: 0.0569781 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 102: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 34%|███▍      | 102/300 [03:25<06:41,  2.03s/it]INFO:model.nn_model_wrapper:training 103  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 103: 0.0609732 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 103: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 103: 0.0674589 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 103: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 34%|███▍      | 103/300 [03:27<06:35,  2.01s/it]INFO:model.nn_model_wrapper:training 104  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 104: 0.0619762 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 104: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 104: 0.0599726 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 104: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 35%|███▍      | 104/300 [03:29<06:36,  2.02s/it]INFO:model.nn_model_wrapper:training 105  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 105: 0.0619763 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 105: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 105: 0.0569781 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 105: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 35%|███▌      | 105/300 [03:31<06:32,  2.01s/it]INFO:model.nn_model_wrapper:training 106  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 106: 0.0611739 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 106: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 106: 0.0539836 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 106: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 35%|███▌      | 106/300 [03:33<06:28,  2.00s/it]INFO:model.nn_model_wrapper:training 107  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 107: 0.0617754 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 107: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 107: 0.0614700 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 107: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 36%|███▌      | 107/300 [03:35<06:28,  2.01s/it]INFO:model.nn_model_wrapper:training 108  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 108: 0.0615754 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 108: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 108: 0.0629671 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 108: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 36%|███▌      | 108/300 [03:37<06:27,  2.02s/it]INFO:model.nn_model_wrapper:training 109  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 109: 0.0611737 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 109: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 109: 0.0599727 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 109: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 36%|███▋      | 109/300 [03:39<06:22,  2.00s/it]INFO:model.nn_model_wrapper:training 110  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 110: 0.0607726 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 110: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 110: 0.0539837 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 110: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 37%|███▋      | 110/300 [03:41<06:17,  1.99s/it]INFO:model.nn_model_wrapper:training 111  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 111: 0.0617757 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 111: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 111: 0.0659617 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 111: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 37%|███▋      | 111/300 [03:43<06:17,  2.00s/it]INFO:model.nn_model_wrapper:training 112  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 112: 0.0615752 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 112: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 112: 0.0614699 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 112: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 37%|███▋      | 112/300 [03:45<06:14,  1.99s/it]INFO:model.nn_model_wrapper:training 113  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 113: 0.0603713 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 113: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 113: 0.0584754 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 113: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 38%|███▊      | 113/300 [03:47<06:18,  2.02s/it]INFO:model.nn_model_wrapper:training 114  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 114: 0.0615752 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 114: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 114: 0.0569782 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 114: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 38%|███▊      | 114/300 [03:49<06:15,  2.02s/it]INFO:model.nn_model_wrapper:training 115  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 115: 0.0615752 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 115: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 115: 0.0584754 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 115: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 38%|███▊      | 115/300 [03:51<06:13,  2.02s/it]INFO:model.nn_model_wrapper:training 116  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 116: 0.0611742 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 116: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 116: 0.0659617 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 116: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 39%|███▊      | 116/300 [03:53<06:11,  2.02s/it]INFO:model.nn_model_wrapper:training 117  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 117: 0.0613748 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 117: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 117: 0.0629671 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 117: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 39%|███▉      | 117/300 [03:55<06:07,  2.01s/it]INFO:model.nn_model_wrapper:training 118  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 118: 0.0599703 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 118: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 118: 0.0644645 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 118: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 39%|███▉      | 118/300 [03:57<06:01,  1.99s/it]INFO:model.nn_model_wrapper:training 119  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 119: 0.0615751 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 119: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 119: 0.0614699 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 119: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 40%|███▉      | 119/300 [03:59<05:59,  1.98s/it]INFO:model.nn_model_wrapper:training 120  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 120: 0.0603715 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 120: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 120: 0.0644645 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 120: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 40%|████      | 120/300 [04:01<06:00,  2.00s/it]INFO:model.nn_model_wrapper:training 121  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 121: 0.0619764 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 121: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 121: 0.0554810 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 121: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 40%|████      | 121/300 [04:03<05:58,  2.00s/it]INFO:model.nn_model_wrapper:training 122  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 122: 0.0615752 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 122: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 122: 0.0614700 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 122: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 41%|████      | 122/300 [04:05<05:59,  2.02s/it]INFO:model.nn_model_wrapper:training 123  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 123: 0.0603714 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 123: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 123: 0.0599728 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 123: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 41%|████      | 123/300 [04:07<05:52,  1.99s/it]INFO:model.nn_model_wrapper:training 124  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 124: 0.0607729 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 124: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 124: 0.0689562 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 124: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 41%|████▏     | 124/300 [04:09<05:50,  1.99s/it]INFO:model.nn_model_wrapper:training 125  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 125: 0.0621769 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 125: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 125: 0.0584757 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 125: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 42%|████▏     | 125/300 [04:11<05:55,  2.03s/it]INFO:model.nn_model_wrapper:training 126  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 126: 0.0609735 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 126: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 126: 0.0689563 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 126: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 42%|████▏     | 126/300 [04:13<05:52,  2.03s/it]INFO:model.nn_model_wrapper:training 127  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 127: 0.0605723 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 127: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 127: 0.0599728 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 127: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 42%|████▏     | 127/300 [04:15<05:48,  2.01s/it]INFO:model.nn_model_wrapper:training 128  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 128: 0.0603714 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 128: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 128: 0.0674591 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 128: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 43%|████▎     | 128/300 [04:17<05:51,  2.04s/it]INFO:model.nn_model_wrapper:training 129  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 129: 0.0607728 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 129: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 129: 0.0614701 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 129: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 43%|████▎     | 129/300 [04:19<05:47,  2.03s/it]INFO:model.nn_model_wrapper:training 130  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 130: 0.0611742 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 130: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 130: 0.0689563 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 130: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 43%|████▎     | 130/300 [04:21<05:48,  2.05s/it]INFO:model.nn_model_wrapper:training 131  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 131: 0.0617760 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 131: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 131: 0.0599728 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 131: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 44%|████▎     | 131/300 [04:23<05:45,  2.05s/it]INFO:model.nn_model_wrapper:training 132  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 132: 0.0607729 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 132: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 132: 0.0569783 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 132: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 44%|████▍     | 132/300 [04:25<05:40,  2.02s/it]INFO:model.nn_model_wrapper:training 133  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 133: 0.0613747 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 133: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 133: 0.0569784 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 133: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 44%|████▍     | 133/300 [04:27<05:40,  2.04s/it]INFO:model.nn_model_wrapper:training 134  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 134: 0.0611741 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 134: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 134: 0.0524867 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 134: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
INFO:model.nn_model_wrapper:======early stopped=====

INFO:model.nn_model_wrapper:train done! best validation metric : -0.05249
****cv 1 / 5 ****
INFO:runner.model.base_runner:****cv 1 / 5 ****
/home/yohyohyonyon/kaggle/vbs-power-line-fault-detection/model/custom_nn.py:256: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  nn.init.xavier_uniform(m.weight.data)
INFO:model.nn_model_wrapper:train with data size: 2323
INFO:model.nn_model_wrapper:valid with data size: 581
  0%|          | 0/300 [00:00<?, ?it/s]INFO:model.nn_model_wrapper:training 1  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 1: 0.2687171 :
INFO:model.nn_model_wrapper:******train score at epoch 1: 0.05443 :
INFO:model.nn_model_wrapper:******valid loss at epoch 1: 0.0582300 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 1: 0.00000 :
INFO:model.nn_model_wrapper:validation metric is improved from -inf to -0.05823
INFO:model.nn_model_wrapper:Checkpoint saved
  0%|          | 1/300 [00:02<10:43,  2.15s/it]INFO:model.nn_model_wrapper:training 2  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 2: 0.0616958 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 2: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 2: 0.0616449 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 2: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
  1%|          | 2/300 [00:04<10:28,  2.11s/it]INFO:model.nn_model_wrapper:training 3  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 3: 0.0617637 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 3: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 3: 0.0601251 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 3: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
  1%|          | 3/300 [00:06<10:25,  2.11s/it]INFO:model.nn_model_wrapper:training 4  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 4: 0.0615367 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 4: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 4: 0.0631495 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 4: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
  1%|▏         | 4/300 [00:08<10:16,  2.08s/it]INFO:model.nn_model_wrapper:training 5  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 5: 0.0613389 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 5: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 5: 0.0707114 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 5: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
  2%|▏         | 5/300 [00:10<10:17,  2.09s/it]INFO:model.nn_model_wrapper:training 6  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 6: 0.0609408 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 6: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 6: 0.0540746 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 6: 0.00000 :
INFO:model.nn_model_wrapper:validation metric is improved from -0.05823 to -0.05407
INFO:model.nn_model_wrapper:Checkpoint saved
  2%|▏         | 6/300 [00:12<10:08,  2.07s/it]INFO:model.nn_model_wrapper:training 7  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 7: 0.0601518 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 7: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 7: 0.0601243 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 7: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
  2%|▏         | 7/300 [00:14<10:02,  2.06s/it]INFO:model.nn_model_wrapper:training 8  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 8: 0.0623171 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 8: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 8: 0.0631492 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 8: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
  3%|▎         | 8/300 [00:16<10:00,  2.06s/it]INFO:model.nn_model_wrapper:training 9  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 9: 0.0611363 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 9: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 9: 0.0631492 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 9: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
  3%|▎         | 9/300 [00:18<09:56,  2.05s/it]INFO:model.nn_model_wrapper:training 10  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 10: 0.0621199 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 10: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 10: 0.0676865 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 10: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
  3%|▎         | 10/300 [00:20<09:53,  2.05s/it]INFO:model.nn_model_wrapper:training 11  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 11: 0.0611357 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 11: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 11: 0.0570995 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 11: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
  4%|▎         | 11/300 [00:22<09:43,  2.02s/it]INFO:model.nn_model_wrapper:training 12  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 12: 0.0607428 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 12: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 12: 0.0707113 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 12: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
  4%|▍         | 12/300 [00:24<09:46,  2.03s/it]INFO:model.nn_model_wrapper:training 13  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 13: 0.0601512 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 13: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 13: 0.0570995 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 13: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
  4%|▍         | 13/300 [00:26<09:57,  2.08s/it]INFO:model.nn_model_wrapper:training 14  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 14: 0.0599546 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 14: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 14: 0.0570995 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 14: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
  5%|▍         | 14/300 [00:28<09:57,  2.09s/it]INFO:model.nn_model_wrapper:training 15  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 15: 0.0599553 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 15: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 15: 0.0555870 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 15: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
  5%|▌         | 15/300 [00:31<10:04,  2.12s/it]INFO:model.nn_model_wrapper:training 16  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 16: 0.0609384 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 16: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 16: 0.0586119 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 16: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
  5%|▌         | 16/300 [00:33<10:05,  2.13s/it]INFO:model.nn_model_wrapper:training 17  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 17: 0.0601515 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 17: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 17: 0.0540746 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 17: 0.00000 :
INFO:model.nn_model_wrapper:validation metric is improved from -0.05407 to -0.05407
INFO:model.nn_model_wrapper:Checkpoint saved
  6%|▌         | 17/300 [00:35<10:03,  2.13s/it]INFO:model.nn_model_wrapper:training 18  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 18: 0.0609389 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 18: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 18: 0.0631492 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 18: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
  6%|▌         | 18/300 [00:37<09:51,  2.10s/it]INFO:model.nn_model_wrapper:training 19  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 19: 0.0611363 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 19: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 19: 0.0631492 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 19: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
  6%|▋         | 19/300 [00:39<09:50,  2.10s/it]INFO:model.nn_model_wrapper:training 20  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 20: 0.0605449 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 20: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 20: 0.0691989 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 20: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
  7%|▋         | 20/300 [00:41<09:52,  2.12s/it]INFO:model.nn_model_wrapper:training 21  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 21: 0.0599549 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 21: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 21: 0.0586119 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 21: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
  7%|▋         | 21/300 [00:43<09:51,  2.12s/it]INFO:model.nn_model_wrapper:training 22  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 22: 0.0607417 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 22: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 22: 0.0691989 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 22: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
  7%|▋         | 22/300 [00:45<09:52,  2.13s/it]INFO:model.nn_model_wrapper:training 23  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 23: 0.0615292 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 23: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 23: 0.0616368 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 23: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
  8%|▊         | 23/300 [00:48<09:49,  2.13s/it]INFO:model.nn_model_wrapper:training 24  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 24: 0.0607423 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 24: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 24: 0.0570995 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 24: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
  8%|▊         | 24/300 [00:50<09:43,  2.11s/it]INFO:model.nn_model_wrapper:training 25  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 25: 0.0611354 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 25: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 25: 0.0691989 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 25: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
  8%|▊         | 25/300 [00:52<09:33,  2.09s/it]INFO:model.nn_model_wrapper:training 26  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 26: 0.0607423 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 26: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 26: 0.0616368 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 26: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
  9%|▊         | 26/300 [00:54<09:30,  2.08s/it]INFO:model.nn_model_wrapper:training 27  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 27: 0.0615292 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 27: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 27: 0.0661740 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 27: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
  9%|▉         | 27/300 [00:56<09:21,  2.06s/it]INFO:model.nn_model_wrapper:training 28  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 28: 0.0609385 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 28: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 28: 0.0631492 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 28: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
  9%|▉         | 28/300 [00:58<09:26,  2.08s/it]INFO:model.nn_model_wrapper:training 29  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 29: 0.0613327 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 29: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 29: 0.0646616 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 29: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 10%|▉         | 29/300 [01:00<09:30,  2.11s/it]INFO:model.nn_model_wrapper:training 30  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 30: 0.0615294 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 30: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 30: 0.0570995 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 30: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 10%|█         | 30/300 [01:02<09:28,  2.10s/it]INFO:model.nn_model_wrapper:training 31  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 31: 0.0613322 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 31: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 31: 0.0555870 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 31: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 10%|█         | 31/300 [01:04<09:20,  2.08s/it]INFO:model.nn_model_wrapper:training 32  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 32: 0.0603484 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 32: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 32: 0.0601243 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 32: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 11%|█         | 32/300 [01:06<09:17,  2.08s/it]INFO:model.nn_model_wrapper:training 33  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 33: 0.0611357 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 33: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 33: 0.0616368 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 33: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 11%|█         | 33/300 [01:08<09:14,  2.08s/it]INFO:model.nn_model_wrapper:training 34  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 34: 0.0605452 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 34: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 34: 0.0631492 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 34: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 11%|█▏        | 34/300 [01:10<09:10,  2.07s/it]INFO:model.nn_model_wrapper:training 35  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 35: 0.0607422 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 35: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 35: 0.0586119 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 35: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 12%|█▏        | 35/300 [01:12<09:08,  2.07s/it]INFO:model.nn_model_wrapper:training 36  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 36: 0.0607432 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 36: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 36: 0.0555870 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 36: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 12%|█▏        | 36/300 [01:14<09:01,  2.05s/it]INFO:model.nn_model_wrapper:training 37  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 37: 0.0615288 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 37: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 37: 0.0586119 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 37: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 12%|█▏        | 37/300 [01:17<09:01,  2.06s/it]INFO:model.nn_model_wrapper:training 38  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 38: 0.0611355 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 38: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 38: 0.0601243 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 38: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 13%|█▎        | 38/300 [01:19<08:59,  2.06s/it]INFO:model.nn_model_wrapper:training 39  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 39: 0.0605453 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 39: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 39: 0.0586119 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 39: 0.00000 :
INFO:model.nn_model_wrapper:validation metric isn't improved
 13%|█▎        | 39/300 [01:21<08:52,  2.04s/it]INFO:model.nn_model_wrapper:training 40  / 300 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 40: 0.0617259 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 40: 0.00000 :
