****cv 0 / 10 ****
INFO:runner.model.base_runner:****cv 0 / 10 ****
/home/yohyohyonyon/kaggle/vbs-power-line-fault-detection/feature/plot_images.py:127: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.plot_meta_df["target"] = self.plot_meta_df["target"].astype("float32")
INFO:model.nn_model_wrapper:train with data size: 2613
INFO:model.nn_model_wrapper:valid with data size: 291
  0%|          | 0/70 [00:00<?, ?it/s]INFO:model.nn_model_wrapper:training 1  / 70 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 1: 0.5465088 :
INFO:model.nn_model_wrapper:******train score at epoch 1: 0.00805 :
INFO:model.nn_model_wrapper:******valid loss at epoch 1: 0.5422276 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 1: 0.00000 :
  1%|▏         | 1/70 [00:18<21:30, 18.70s/it]INFO:model.nn_model_wrapper:training 2  / 70 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 2: 0.3061636 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 2: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 2: 0.3110728 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 2: 0.00000 :
  3%|▎         | 2/70 [00:35<20:26, 18.04s/it]INFO:model.nn_model_wrapper:training 3  / 70 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 3: 0.2324593 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 3: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 3: 0.2340857 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 3: 0.00000 :
  4%|▍         | 3/70 [00:50<19:19, 17.31s/it]INFO:model.nn_model_wrapper:training 4  / 70 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 4: 0.2222590 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 4: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 4: 0.2329145 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 4: 0.00000 :
  6%|▌         | 4/70 [01:06<18:35, 16.90s/it]INFO:model.nn_model_wrapper:training 5  / 70 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 5: 0.2037887 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 5: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 5: 0.2394058 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 5: 0.00000 :
  7%|▋         | 5/70 [01:22<18:00, 16.62s/it]INFO:model.nn_model_wrapper:training 6  / 70 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 6: 0.1934232 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 6: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 6: 0.2340731 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 6: 0.00000 :
  9%|▊         | 6/70 [01:38<17:24, 16.33s/it]INFO:model.nn_model_wrapper:training 7  / 70 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 7: 0.1706263 :
INFO:model.nn_model_wrapper:******train score at epoch 7: 0.09839 :
INFO:model.nn_model_wrapper:******valid loss at epoch 7: 0.2101843 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 7: 0.00000 :
 10%|█         | 7/70 [01:53<16:52, 16.07s/it]INFO:model.nn_model_wrapper:training 8  / 70 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 8: 0.1622793 :
INFO:model.nn_model_wrapper:******train score at epoch 8: 0.19154 :
INFO:model.nn_model_wrapper:******valid loss at epoch 8: 0.1833244 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 8: 0.00000 :
 11%|█▏        | 8/70 [02:10<16:48, 16.27s/it]INFO:model.nn_model_wrapper:training 9  / 70 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 9: 0.1575261 :
INFO:model.nn_model_wrapper:******train score at epoch 9: 0.32400 :
INFO:model.nn_model_wrapper:******valid loss at epoch 9: 0.1690726 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 9: 0.00000 :
 13%|█▎        | 9/70 [02:27<16:40, 16.40s/it]INFO:model.nn_model_wrapper:training 10  / 70 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 10: 0.1416736 :
INFO:model.nn_model_wrapper:******train score at epoch 10: 0.37469 :
INFO:model.nn_model_wrapper:******valid loss at epoch 10: 0.1644018 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 10: 0.00000 :
INFO:model.nn_model_wrapper:======early stopped=====

INFO:model.nn_model_wrapper:train done!
****cv 1 / 10 ****
INFO:runner.model.base_runner:****cv 1 / 10 ****
/home/yohyohyonyon/kaggle/vbs-power-line-fault-detection/feature/plot_images.py:127: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.plot_meta_df["target"] = self.plot_meta_df["target"].astype("float32")
INFO:model.nn_model_wrapper:train with data size: 2613
INFO:model.nn_model_wrapper:valid with data size: 291
  0%|          | 0/70 [00:00<?, ?it/s]INFO:model.nn_model_wrapper:training 1  / 70 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 1: 0.5371920 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 1: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 1: 0.5417802 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 1: 0.00000 :
  1%|▏         | 1/70 [00:15<17:55, 15.58s/it]INFO:model.nn_model_wrapper:training 2  / 70 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 2: 0.3063968 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 2: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 2: 0.3413717 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 2: 0.00000 :
  3%|▎         | 2/70 [00:31<17:50, 15.74s/it]INFO:model.nn_model_wrapper:training 3  / 70 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 3: 0.2453736 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 3: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 3: 0.2452985 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 3: 0.00000 :
  4%|▍         | 3/70 [00:48<17:52, 16.01s/it]INFO:model.nn_model_wrapper:training 4  / 70 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 4: 0.2210006 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 4: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 4: 0.2275391 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 4: 0.00000 :
  6%|▌         | 4/70 [01:04<17:37, 16.02s/it]INFO:model.nn_model_wrapper:training 5  / 70 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 5: 0.2133553 :
INFO:model.nn_model_wrapper:******train score at epoch 5: 0.07252 :
INFO:model.nn_model_wrapper:******valid loss at epoch 5: 0.2306386 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 5: 0.00000 :
  7%|▋         | 5/70 [01:20<17:15, 15.93s/it]INFO:model.nn_model_wrapper:training 6  / 70 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 6: 0.1801110 :
INFO:model.nn_model_wrapper:******train score at epoch 6: 0.24660 :
INFO:model.nn_model_wrapper:******valid loss at epoch 6: 0.2217171 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 6: 0.00000 :
  9%|▊         | 6/70 [01:35<16:55, 15.86s/it]INFO:model.nn_model_wrapper:training 7  / 70 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 7: 0.1703104 :
INFO:model.nn_model_wrapper:******train score at epoch 7: 0.24118 :
INFO:model.nn_model_wrapper:******valid loss at epoch 7: 0.1972538 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 7: 0.00000 :
 10%|█         | 7/70 [01:52<16:53, 16.09s/it]INFO:model.nn_model_wrapper:training 8  / 70 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 8: 0.1449261 :
INFO:model.nn_model_wrapper:******train score at epoch 8: 0.34519 :
INFO:model.nn_model_wrapper:******valid loss at epoch 8: 0.1743196 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 8: 0.00000 :
 11%|█▏        | 8/70 [02:08<16:46, 16.23s/it]INFO:model.nn_model_wrapper:training 9  / 70 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 9: 0.1600417 :
INFO:model.nn_model_wrapper:******train score at epoch 9: 0.29464 :
INFO:model.nn_model_wrapper:******valid loss at epoch 9: 0.1574529 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 9: 0.00000 :
 13%|█▎        | 9/70 [02:25<16:32, 16.28s/it]INFO:model.nn_model_wrapper:training 10  / 70 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 10: 0.1539814 :
INFO:model.nn_model_wrapper:******train score at epoch 10: 0.40451 :
INFO:model.nn_model_wrapper:******valid loss at epoch 10: 0.1437133 :
INFO:model.nn_model_wrapper:******valid score at epoch 10: 0.22869 :
INFO:model.nn_model_wrapper:validation score is improved from 0.00000 to 0.22869
INFO:model.nn_model_wrapper:Checkpoint saved
 14%|█▍        | 10/70 [02:41<16:09, 16.15s/it]INFO:model.nn_model_wrapper:training 11  / 70 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 11: 0.1330033 :
INFO:model.nn_model_wrapper:******train score at epoch 11: 0.39299 :
INFO:model.nn_model_wrapper:******valid loss at epoch 11: 0.1429075 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 11: 0.00000 :
 16%|█▌        | 11/70 [02:57<15:56, 16.21s/it]INFO:model.nn_model_wrapper:training 12  / 70 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 12: 0.1437460 :
INFO:model.nn_model_wrapper:******train score at epoch 12: 0.40171 :
INFO:model.nn_model_wrapper:******valid loss at epoch 12: 0.1272299 :
INFO:model.nn_model_wrapper:******valid score at epoch 12: 0.32397 :
INFO:model.nn_model_wrapper:validation score is improved from 0.22869 to 0.32397
INFO:model.nn_model_wrapper:Checkpoint saved
 17%|█▋        | 12/70 [03:13<15:41, 16.24s/it]INFO:model.nn_model_wrapper:training 13  / 70 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 13: 0.1256963 :
INFO:model.nn_model_wrapper:******train score at epoch 13: 0.53577 :
INFO:model.nn_model_wrapper:******valid loss at epoch 13: 0.1198398 :
INFO:model.nn_model_wrapper:******valid score at epoch 13: 0.39747 :
INFO:model.nn_model_wrapper:validation score is improved from 0.32397 to 0.39747
INFO:model.nn_model_wrapper:Checkpoint saved
 19%|█▊        | 13/70 [03:30<15:25, 16.24s/it]INFO:model.nn_model_wrapper:training 14  / 70 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 14: 0.1205024 :
INFO:model.nn_model_wrapper:******train score at epoch 14: 0.53834 :
INFO:model.nn_model_wrapper:******valid loss at epoch 14: 0.1162458 :
INFO:model.nn_model_wrapper:******valid score at epoch 14: 0.39747 :
 20%|██        | 14/70 [03:46<15:11, 16.29s/it]INFO:model.nn_model_wrapper:training 15  / 70 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 15: 0.1081516 :
INFO:model.nn_model_wrapper:******train score at epoch 15: 0.53008 :
INFO:model.nn_model_wrapper:******valid loss at epoch 15: 0.1290070 :
INFO:model.nn_model_wrapper:******valid score at epoch 15: 0.22869 :
 21%|██▏       | 15/70 [04:02<14:58, 16.33s/it]INFO:model.nn_model_wrapper:training 16  / 70 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 16: 0.1069808 :
INFO:model.nn_model_wrapper:******train score at epoch 16: 0.61594 :
INFO:model.nn_model_wrapper:******valid loss at epoch 16: 0.1705836 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 16: 0.00000 :
 23%|██▎       | 16/70 [04:19<14:38, 16.27s/it]INFO:model.nn_model_wrapper:training 17  / 70 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 17: 0.0985805 :
INFO:model.nn_model_wrapper:******train score at epoch 17: 0.64952 :
INFO:model.nn_model_wrapper:******valid loss at epoch 17: 0.1193629 :
INFO:model.nn_model_wrapper:******valid score at epoch 17: 0.39747 :
 24%|██▍       | 17/70 [04:35<14:18, 16.20s/it]INFO:model.nn_model_wrapper:training 18  / 70 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 18: 0.1099109 :
INFO:model.nn_model_wrapper:******train score at epoch 18: 0.66287 :
INFO:model.nn_model_wrapper:******valid loss at epoch 18: 0.1206134 :
INFO:model.nn_model_wrapper:******valid score at epoch 18: 0.32397 :
 26%|██▌       | 18/70 [04:51<14:05, 16.25s/it]INFO:model.nn_model_wrapper:training 19  / 70 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 19: 0.0755353 :
INFO:model.nn_model_wrapper:******train score at epoch 19: 0.74427 :
INFO:model.nn_model_wrapper:******valid loss at epoch 19: 0.0981839 :
INFO:model.nn_model_wrapper:******valid score at epoch 19: 0.61141 :
INFO:model.nn_model_wrapper:validation score is improved from 0.39747 to 0.61141
INFO:model.nn_model_wrapper:Checkpoint saved
 27%|██▋       | 19/70 [05:07<13:46, 16.20s/it]INFO:model.nn_model_wrapper:training 20  / 70 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 20: 0.0749074 :
INFO:model.nn_model_wrapper:******train score at epoch 20: 0.77292 :
INFO:model.nn_model_wrapper:******valid loss at epoch 20: 0.1056067 :
INFO:model.nn_model_wrapper:******valid score at epoch 20: 0.45976 :
 29%|██▊       | 20/70 [05:24<13:38, 16.36s/it]INFO:model.nn_model_wrapper:training 21  / 70 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 21: 0.0618596 :
INFO:model.nn_model_wrapper:******train score at epoch 21: 0.78901 :
INFO:model.nn_model_wrapper:******valid loss at epoch 21: 0.0998963 :
INFO:model.nn_model_wrapper:******valid score at epoch 21: 0.51831 :
 30%|███       | 21/70 [05:40<13:19, 16.31s/it]INFO:model.nn_model_wrapper:training 22  / 70 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 22: 0.0571120 :
INFO:model.nn_model_wrapper:******train score at epoch 22: 0.84393 :
INFO:model.nn_model_wrapper:******valid loss at epoch 22: 0.1092332 :
INFO:model.nn_model_wrapper:******valid score at epoch 22: 0.51831 :
 31%|███▏      | 22/70 [05:56<12:56, 16.18s/it]INFO:model.nn_model_wrapper:training 23  / 70 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 23: 0.0468850 :
INFO:model.nn_model_wrapper:******train score at epoch 23: 0.90671 :
INFO:model.nn_model_wrapper:******valid loss at epoch 23: 0.1086856 :
INFO:model.nn_model_wrapper:******valid score at epoch 23: 0.51831 :
 33%|███▎      | 23/70 [06:12<12:34, 16.05s/it]INFO:model.nn_model_wrapper:training 24  / 70 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 24: 0.0344299 :
INFO:model.nn_model_wrapper:******train score at epoch 24: 0.93162 :
INFO:model.nn_model_wrapper:******valid loss at epoch 24: 0.1134480 :
INFO:model.nn_model_wrapper:******valid score at epoch 24: 0.51493 :
 34%|███▍      | 24/70 [06:28<12:28, 16.28s/it]INFO:model.nn_model_wrapper:training 25  / 70 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 25: 0.0313117 :
INFO:model.nn_model_wrapper:******train score at epoch 25: 0.93513 :
INFO:model.nn_model_wrapper:******valid loss at epoch 25: 0.1225343 :
INFO:model.nn_model_wrapper:******valid score at epoch 25: 0.51493 :
 36%|███▌      | 25/70 [06:44<12:04, 16.09s/it]INFO:model.nn_model_wrapper:training 26  / 70 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 26: 0.0258975 :
INFO:model.nn_model_wrapper:******train score at epoch 26: 0.95943 :
INFO:model.nn_model_wrapper:******valid loss at epoch 26: 0.1598558 :
INFO:model.nn_model_wrapper:******valid score at epoch 26: 0.39747 :
 37%|███▋      | 26/70 [07:00<11:49, 16.12s/it]INFO:model.nn_model_wrapper:training 27  / 70 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 27: 0.0210791 :
INFO:model.nn_model_wrapper:******train score at epoch 27: 0.97987 :
INFO:model.nn_model_wrapper:******valid loss at epoch 27: 0.1231477 :
INFO:model.nn_model_wrapper:******valid score at epoch 27: 0.56506 :
 39%|███▊      | 27/70 [07:16<11:33, 16.14s/it]INFO:model.nn_model_wrapper:training 28  / 70 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 28: 0.0200160 :
INFO:model.nn_model_wrapper:******train score at epoch 28: 0.98662 :
INFO:model.nn_model_wrapper:******valid loss at epoch 28: 0.1138010 :
INFO:model.nn_model_wrapper:******valid score at epoch 28: 0.46468 :
 40%|████      | 28/70 [07:33<11:16, 16.11s/it]INFO:model.nn_model_wrapper:training 29  / 70 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 29: 0.0167266 :
INFO:model.nn_model_wrapper:******train score at epoch 29: 0.99333 :
INFO:model.nn_model_wrapper:******valid loss at epoch 29: 0.1059443 :
INFO:model.nn_model_wrapper:******valid score at epoch 29: 0.56506 :
INFO:model.nn_model_wrapper:======early stopped=====

INFO:model.nn_model_wrapper:train done!
****cv 2 / 10 ****
INFO:runner.model.base_runner:****cv 2 / 10 ****
/home/yohyohyonyon/kaggle/vbs-power-line-fault-detection/feature/plot_images.py:127: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.plot_meta_df["target"] = self.plot_meta_df["target"].astype("float32")
INFO:model.nn_model_wrapper:train with data size: 2613
INFO:model.nn_model_wrapper:valid with data size: 291
  0%|          | 0/70 [00:00<?, ?it/s]INFO:model.nn_model_wrapper:training 1  / 70 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 1: 0.5236908 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 1: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 1: 0.6014776 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 1: 0.00000 :
  1%|▏         | 1/70 [00:16<18:36, 16.18s/it]INFO:model.nn_model_wrapper:training 2  / 70 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 2: 0.3196260 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 2: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 2: 0.3699268 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 2: 0.00000 :
  3%|▎         | 2/70 [00:31<18:12, 16.06s/it]INFO:model.nn_model_wrapper:training 3  / 70 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 3: 0.2448897 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 3: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 3: 0.2498439 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 3: 0.00000 :
  4%|▍         | 3/70 [00:48<18:02, 16.15s/it]INFO:model.nn_model_wrapper:training 4  / 70 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 4: 0.2248654 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******train score at epoch 4: 0.00000 :
INFO:model.nn_model_wrapper:******valid loss at epoch 4: 0.2303973 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 4: 0.00000 :
  6%|▌         | 4/70 [01:04<17:36, 16.01s/it]INFO:model.nn_model_wrapper:training 5  / 70 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 5: 0.2045158 :
INFO:model.nn_model_wrapper:******train score at epoch 5: -0.00500 :
INFO:model.nn_model_wrapper:******valid loss at epoch 5: 0.2372245 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 5: 0.00000 :
  7%|▋         | 5/70 [01:20<17:21, 16.03s/it]INFO:model.nn_model_wrapper:training 6  / 70 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 6: 0.1910821 :
INFO:model.nn_model_wrapper:******train score at epoch 6: 0.12844 :
INFO:model.nn_model_wrapper:******valid loss at epoch 6: 0.2248882 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 6: 0.00000 :
  9%|▊         | 6/70 [01:36<17:13, 16.16s/it]INFO:model.nn_model_wrapper:training 7  / 70 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 7: 0.1742762 :
INFO:model.nn_model_wrapper:******train score at epoch 7: 0.18610 :
INFO:model.nn_model_wrapper:******valid loss at epoch 7: 0.2054989 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 7: 0.00000 :
 10%|█         | 7/70 [01:52<16:55, 16.11s/it]INFO:model.nn_model_wrapper:training 8  / 70 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 8: 0.1639889 :
INFO:model.nn_model_wrapper:******train score at epoch 8: 0.32201 :
INFO:model.nn_model_wrapper:******valid loss at epoch 8: 0.1914468 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 8: 0.00000 :
 11%|█▏        | 8/70 [02:09<16:45, 16.22s/it]INFO:model.nn_model_wrapper:training 9  / 70 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 9: 0.1598972 :
INFO:model.nn_model_wrapper:******train score at epoch 9: 0.35422 :
INFO:model.nn_model_wrapper:******valid loss at epoch 9: 0.1720343 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 9: 0.00000 :
 13%|█▎        | 9/70 [02:25<16:35, 16.31s/it]INFO:model.nn_model_wrapper:training 10  / 70 epochs
INFO:model.nn_model_wrapper:******train loss at epoch 10: 0.1371205 :
INFO:model.nn_model_wrapper:******train score at epoch 10: 0.41618 :
INFO:model.nn_model_wrapper:******valid loss at epoch 10: 0.1664999 :
/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:543: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
INFO:model.nn_model_wrapper:******valid score at epoch 10: 0.00000 :
INFO:model.nn_model_wrapper:======early stopped=====
Traceback (most recent call last):
  File "runner/model/train/resnet10_window_800000_kfold.py", line 17, in <module>
    runner(plot_root, save_dir=save_dir, transformers=DefaultTransformers())
  File "/home/yohyohyonyon/kaggle/vbs-power-line-fault-detection/runner/model/base_runner.py", line 130, in __call__
    self._train_cv(i, train_index, test_index)
  File "/home/yohyohyonyon/kaggle/vbs-power-line-fault-detection/runner/model/base_runner.py", line 148, in _train_cv
    num_workers=n_cpus)
  File "/home/yohyohyonyon/kaggle/vbs-power-line-fault-detection/model/nn_model_wrapper.py", line 112, in train
    self.model.load_state_dict(torch.load(self.save_path))
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 769, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DataParallel:
	Unexpected key(s) in state_dict: "module.0.layer1.1.conv1.weight", "module.0.layer1.1.bn1.weight", "module.0.layer1.1.bn1.bias", "module.0.layer1.1.bn1.running_mean", "module.0.layer1.1.bn1.running_var", "module.0.layer1.1.bn1.num_batches_tracked", "module.0.layer1.1.conv2.weight", "module.0.layer1.1.bn2.weight", "module.0.layer1.1.bn2.bias", "module.0.layer1.1.bn2.running_mean", "module.0.layer1.1.bn2.running_var", "module.0.layer1.1.bn2.num_batches_tracked", "module.0.layer2.1.conv1.weight", "module.0.layer2.1.bn1.weight", "module.0.layer2.1.bn1.bias", "module.0.layer2.1.bn1.running_mean", "module.0.layer2.1.bn1.running_var", "module.0.layer2.1.bn1.num_batches_tracked", "module.0.layer2.1.conv2.weight", "module.0.layer2.1.bn2.weight", "module.0.layer2.1.bn2.bias", "module.0.layer2.1.bn2.running_mean", "module.0.layer2.1.bn2.running_var", "module.0.layer2.1.bn2.num_batches_tracked", "module.0.layer3.1.conv1.weight", "module.0.layer3.1.bn1.weight", "module.0.layer3.1.bn1.bias", "module.0.layer3.1.bn1.running_mean", "module.0.layer3.1.bn1.running_var", "module.0.layer3.1.bn1.num_batches_tracked", "module.0.layer3.1.conv2.weight", "module.0.layer3.1.bn2.weight", "module.0.layer3.1.bn2.bias", "module.0.layer3.1.bn2.running_mean", "module.0.layer3.1.bn2.running_var", "module.0.layer3.1.bn2.num_batches_tracked", "module.0.layer4.1.conv1.weight", "module.0.layer4.1.bn1.weight", "module.0.layer4.1.bn1.bias", "module.0.layer4.1.bn1.running_mean", "module.0.layer4.1.bn1.running_var", "module.0.layer4.1.bn1.num_batches_tracked", "module.0.layer4.1.conv2.weight", "module.0.layer4.1.bn2.weight", "module.0.layer4.1.bn2.bias", "module.0.layer4.1.bn2.running_mean", "module.0.layer4.1.bn2.running_var", "module.0.layer4.1.bn2.num_batches_tracked". 
